"""Create notebooks/synth_data_gen.ipynb"""
import json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def md(src): return {"cell_type": "markdown", "metadata": {}, "source": src}
def code(src): return {"cell_type": "code", "execution_count": None,
                       "metadata": {}, "outputs": [], "source": src}

cells = []

cells.append(md(
    "# synth_data_gen.ipynb\n\n"
    "Sinh du lieu NER tong hop (BANGIAO §3-§6). Chay tren Kaggle GPU T4 x2, Internet ON.\n\n"
    "**Datasets can add:** KB files tu repo (fakeer/kb/)\n\n"
    "**Output:** `output_json/*.json` (schema: `[{text, type, position:[start,end]}]`)"
))

# ── Cell 1: setup ─────────────────────────────────────────────────────────
cells.append(code(
    "import os, sys, subprocess\n"
    "os.environ.setdefault('VLLM_WORKER_MULTIPROC_METHOD', 'spawn')\n"
    "os.environ.setdefault('PYTORCH_CUDA_ALLOC_CONF', 'expandable_segments:True')\n"
    "subprocess.run([sys.executable, '-m', 'pip', 'install', '-q', 'vllm'], check=True)\n"
    "\n"
    "REPO = 'https://github.com/Khanhhh239/fakeer.git'\n"
    "if not os.path.exists('fakeer'):\n"
    "    subprocess.run(['git', 'clone', '-q', REPO], check=True)\n"
    "subprocess.run(['git', '-C', 'fakeer', 'pull', '-q', 'origin', 'main'])\n"
    "\n"
    "sys.path.insert(0, 'fakeer/src')\n"
    "import glob, json, random, re, time\n"
    "os.makedirs('/kaggle/working/output_json', exist_ok=True)\n"
    "print('Setup xong')"
))

# ── Cell 2: load Qwen (copy logic tu ner_v2_phase2 Cell 2) ────────────────
cells.append(code(
    "import torch, inspect\n"
    "from vllm import LLM, SamplingParams\n"
    "from transformers import AutoTokenizer\n"
    "\n"
    "_ngpu = max(1, torch.cuda.device_count())\n"
    "print(f'{_ngpu} GPU kha dung')\n"
    "\n"
    "def _mk(model, tp, util):\n"
    "    want = dict(model=model, dtype='float16', max_model_len=3072,\n"
    "                gpu_memory_utilization=util, tensor_parallel_size=tp,\n"
    "                enforce_eager=True, disable_custom_all_reduce=True)\n"
    "    ok = set(inspect.signature(LLM.__init__).parameters)\n"
    "    want = {k: v for k, v in want.items() if k in ok}\n"
    "    return LLM(**want)\n"
    "\n"
    "LLM_MODEL = 'Qwen/Qwen3-8B'\n"
    "_plans = [(LLM_MODEL, _ngpu, 0.90), (LLM_MODEL, _ngpu, 0.80),\n"
    "          (LLM_MODEL, _ngpu, 0.70), ('Qwen/Qwen2.5-7B-Instruct', _ngpu, 0.85)]\n"
    "llm = None\n"
    "for _m, _tp, _u in _plans:\n"
    "    try:\n"
    "        print(f'Thu {_m} | TP={_tp} | util={_u}')\n"
    "        llm = _mk(_m, _tp, _u)\n"
    "        LLM_MODEL = _m\n"
    "        break\n"
    "    except Exception as e:\n"
    "        print('  x', type(e).__name__, str(e)[:120])\n"
    "assert llm is not None, 'Khong nap duoc LLM nao'\n"
    "qtok = AutoTokenizer.from_pretrained(LLM_MODEL)\n"
    "print('DUNG:', LLM_MODEL)"
))

# ── Cell 3: T0 kho nguon ─────────────────────────────────────────────────
cells.append(code(
    "from synth_source import load_chandoan, load_trieuchung, load_thuoc, _load_txt\n"
    "\n"
    "chandoan_pool = load_chandoan()\n"
    "trieuchung_pool = load_trieuchung()\n"
    "thuoc_pool = load_thuoc()\n"
    "xn_names = _load_txt('xetnghiem_ten.txt')\n"
    "am_thuoc = _load_txt('am_thuoc_gia.txt')\n"
    "am_xetnghiem = _load_txt('am_xetnghiem_gia.txt')\n"
    "heading_ls = _load_txt('heading_lamsang.txt')\n"
    "heading_hd = _load_txt('heading_hoidap.txt')\n"
    "\n"
    "print(f'Chan doan: {len(chandoan_pool)}, Trieu chung: {len(trieuchung_pool)}')\n"
    "print(f'Thuoc: {len(thuoc_pool)}, XN ten: {len(xn_names)}')\n"
    "print(f'Am thuoc: {len(am_thuoc)}, Am XN: {len(am_xetnghiem)}')"
))

# ── Cell 4: T1 prompt (nguyen van tu BANGIAO §3.2) ─────────────────────────
PROMPT_T1 = (
    "CHI TRA LOI BANG TIENG VIET. Khong dung chu Han, chu Trung Quoc, tieng Anh.\n\n"
    "Ban la bac si Viet Nam. Voi chan doan duoc cho, liet ke cac khai niem y khoa "
    "thuong di kem trong benh an.\n\n"
    "DINH DANG: moi dong mot muc, dung dang MA|noi dung\n"
    "  TC = trieu chung nguoi benh cam nhan hoac bac si quan sat duoc\n"
    "  TH = ten thuoc dieu tri\n"
    "  TX = ten xet nghiem / tham do / thu thuat chan doan\n\n"
    "SO LUONG: 5 dong TC, 3 dong TH, 3 dong TX. Tong dung 11 dong.\n\n"
    "QUY TAC:\n"
    "1. Chi ghi TEN, khong ghi dong tu di kem.\n"
    "2. TH phai la ten thuoc CO THAT. Khong bia.\n"
    "   DUNG: TH|paracetamol, TH|khang sinh, TH|corticoid\n"
    "3. TX phai la TEN mot xet nghiem cu the, KHONG phai mo ta cach lam.\n"
    "   DUNG: TX|cong thuc mau, TX|sieu am o bung\n"
    "4. TC phai la dieu nguoi benh CAM THAY hoac bac si THAY.\n"
    "   DUNG: TC|sot cao, TC|dau vung thuong vi\n"
    "5. Moi muc phai lien quan TRUC TIEP toi chan doan da cho.\n"
    "6. Moi muc 1-5 tu, viet nhu bac si ghi benh an.\n"
    "7. KHONG chu thich ten nuoc ngoai trong ngoac.\n"
    "8. Viet xong 11 dong thi DUNG. Khong giai thich.\n\n"
    "BAY GIO LAM VOI CHAN DOAN: \"{diagnosis}\"\n\n"
    "Nhac lai: chi tieng Viet. Khong chu Han. Khong tieng Anh."
)

cells.append(code(
    "PROMPT_T1_TEMPLATE = " + repr(PROMPT_T1) + "\n"
    "\n"
    "def build_t1_prompt(diagnosis):\n"
    "    messages = [{'role': 'user',\n"
    "                 'content': PROMPT_T1_TEMPLATE.format(diagnosis=diagnosis)}]\n"
    "    p = qtok.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n"
    "    # Tat thinking Qwen3\n"
    "    if '/no_think' not in p:\n"
    "        p += '/no_think\\n'\n"
    "    return p\n"
    "\n"
    "def parse_t1_response(text):\n"
    "    tc, th, tx = [], [], []\n"
    "    for line in text.strip().split('\\n'):\n"
    "        line = line.strip()\n"
    "        if '|' not in line: continue\n"
    "        code_, _, content = line.partition('|')\n"
    "        code_ = code_.strip().upper(); content = content.strip()\n"
    "        if not content or len(content) < 2: continue\n"
    "        if code_ == 'TC': tc.append(content)\n"
    "        elif code_ == 'TH': th.append(content)\n"
    "        elif code_ == 'TX': tx.append(content)\n"
    "    return {'tc': tc[:5], 'th': th[:3], 'tx': tx[:3]}\n"
    "\n"
    "# Phan tang: moi chuong ICD chon ~5 chan doan -> ~100 chan doan tong\n"
    "from collections import defaultdict\n"
    "by_ch = defaultdict(list)\n"
    "for d in chandoan_pool:\n"
    "    by_ch[d['chapter']].append(d)\n"
    "sample_diag = []\n"
    "for ch, items in by_ch.items():\n"
    "    sample_diag.extend(random.sample(items, min(5, len(items))))\n"
    "random.shuffle(sample_diag)\n"
    "print(f'Chan doan mau: {len(sample_diag)}')\n"
    "\n"
    "t1_prompts = [build_t1_prompt(d['term']) for d in sample_diag]\n"
    "t0 = time.time()\n"
    "t1_outs = llm.generate(t1_prompts, SamplingParams(temperature=0.3, max_tokens=300))\n"
    "print(f'T1 xong {len(t1_outs)} kich ban trong {time.time()-t0:.0f}s')\n"
    "\n"
    "scenarios = []\n"
    "for d, out in zip(sample_diag, t1_outs):\n"
    "    parsed = parse_t1_response(out.outputs[0].text)\n"
    "    if len(parsed['tc']) >= 3:\n"
    "        scenarios.append({'diagnosis': d, 'scenario': parsed})\n"
    "print(f'Kich ban hop le: {len(scenarios)} / {len(sample_diag)}')\n"
    "print('Vi du:', scenarios[0] if scenarios else None)"
))

# ── Cell 5: T2B prompt (nguyen van tu BANGIAO §3.4) ─────────────────────
PROMPT_T2B = (
    "CHI VIET BANG TIENG VIET. Khong dung chu Han, chu Trung Quoc. "
    "Duoc phep dung thuat ngu y khoa chuan viet bang chu La-tinh.\n\n"
    "Ban la bien tap vien chuyen muc tu van suc khoe cua mot trang web y te Viet Nam.\n"
    "Viet MOT BAI tu van hoan chinh.\n\n"
    "Bai gom dung cac phan sau, viet lien mach:\n\n"
    "Cau hoi tu nguoi dung:\n"
    "(4 den 6 cau, nguoi benh tu ke: hoan canh, kho chiu ra sao, lo lang gi, roi hoi)\n\n"
    "Cau tra loi cua bac si:\n"
    "Chao ban,\n"
    "1. {tieu_de_1}\n(4 den 6 cau)\n"
    "2. {tieu_de_2}\n(4 den 6 cau)\n"
    "3. {tieu_de_3}\n(4 den 6 cau)\n"
    "4. {tieu_de_4}\n(4 den 6 cau)\n"
    "Tran trong!\n\n"
    "CAC CUM SAU PHAI XUAT HIEN NGUYEN VAN trong bai, khong sua mot chu:\n"
    "{danh_sach_cum}\n"
    "- {bait_thuoc}\n"
    "- {bait_xetnghiem}\n\n"
    "QUY TAC:\n"
    "- Tong bai 500 den 700 tu.\n"
    "- Mo phong loi go: dinh lien {n_glue} cho (bo dau cach).\n"
    "- Chen dau sao {n_mask} cho, vi du 'Khang sinh nhom ***'.\n"
    "- Chi ap dung loi o phan van xuoi, KHONG duong vao cac cum bat buoc va bait.\n"
    "- Cam cau tran an rong. Cam viet doi thoai qua lai.\n"
    "- Khong dung gach dau dong trong phan tra loi.\n\n"
    "Nhac lai: viet tieng Viet, thuoc/xet nghiem giu ten quoc te chuan."
)

cells.append(code(
    "from synth_anchor import anchor_all, validate_document\n"
    "\n"
    "PROMPT_T2B = " + repr(PROMPT_T2B) + "\n"
    "\n"
    "TYPE_MAP = {\n"
    "    'CHAN_DOAN': 'CHAN_DOAN', 'TRIEU_CHUNG': 'TRIEU_CHUNG',\n"
    "    'THUOC': 'THUOC', 'TEN_XET_NGHIEM': 'TEN_XET_NGHIEM',\n"
    "    'KET_QUA_XET_NGHIEM': 'KET_QUA_XET_NGHIEM',\n"
    "}\n"
    "\n"
    "def build_t2b_prompt(scenario):\n"
    "    sc = scenario['scenario']\n"
    "    diag = scenario['diagnosis']['term']\n"
    "    ents = [(diag, 'CHAN_DOAN')]\n"
    "    for t in sc['tc']: ents.append((t, 'TRIEU_CHUNG'))\n"
    "    for t in sc['th']: ents.append((t, 'THUOC'))\n"
    "    for t in sc['tx']: ents.append((t, 'TEN_XET_NGHIEM'))\n"
    "    for xn in random.sample(xn_names, min(3, len(xn_names))):\n"
    "        ents.append((xn, 'TEN_XET_NGHIEM'))\n"
    "    random.shuffle(ents)\n"
    "    ents = ents[:15]\n"
    "    bt = random.choice(am_thuoc)\n"
    "    bx = random.choice(am_xetnghiem)\n"
    "    n_glue = random.randint(1, 5)\n"
    "    n_mask = random.randint(1, 3)\n"
    "    tds_pool = [\n"
    "        f'{diag} la benh gi', f'Trieu chung cua {diag}',\n"
    "        f'Nguyen nhan gay {diag}', f'Dieu tri {diag}',\n"
    "        f'Phong ngua {diag}', 'Khi nao can gap bac si'\n"
    "    ]\n"
    "    tds = random.sample(tds_pool, 4)\n"
    "    danh_sach = '\\n'.join(f'- {s}' for s, _ in ents)\n"
    "    prompt_text = PROMPT_T2B.format(\n"
    "        danh_sach_cum=danh_sach, bait_thuoc=bt, bait_xetnghiem=bx,\n"
    "        n_glue=n_glue, n_mask=n_mask,\n"
    "        tieu_de_1=tds[0], tieu_de_2=tds[1],\n"
    "        tieu_de_3=tds[2], tieu_de_4=tds[3],\n"
    "    )\n"
    "    messages = [{'role': 'user', 'content': prompt_text}]\n"
    "    p = qtok.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)\n"
    "    if '/no_think' not in p:\n"
    "        p += '/no_think\\n'\n"
    "    return p, ents, bt, bx\n"
    "\n"
    "t2b_inputs = []\n"
    "for sc in scenarios:\n"
    "    p, req, bt, bx = build_t2b_prompt(sc)\n"
    "    t2b_inputs.append((p, req, bt, bx, sc))\n"
    "\n"
    "t2b_prompts = [x[0] for x in t2b_inputs]\n"
    "t0 = time.time()\n"
    "t2b_outs = llm.generate(t2b_prompts, SamplingParams(temperature=0.7, max_tokens=900))\n"
    "print(f'T2B xong {len(t2b_outs)} bai trong {time.time()-t0:.0f}s')"
))

# ── Cell 6: neo nhan + validate + ghi output_json ──────────────────────────
cells.append(code(
    "saved = 0\n"
    "reject_log = {}\n"
    "\n"
    "for i, (t2b_out, (_, req, bait_t, bait_x, sc)) in enumerate(\n"
    "        zip(t2b_outs, t2b_inputs)):\n"
    "    text = t2b_out.outputs[0].text.strip()\n"
    "    if not text:\n"
    "        reject_log['empty'] = reject_log.get('empty', 0) + 1\n"
    "        continue\n"
    "\n"
    "    ents = anchor_all(text, req, bait=[bait_t, bait_x])\n"
    "    if ents is None:\n"
    "        reject_log['anchor<60%'] = reject_log.get('anchor<60%', 0) + 1\n"
    "        continue\n"
    "\n"
    "    ok, reason = validate_document(\n"
    "        text, ents, bait_thuoc=bait_t, bait_xetnghiem=bait_x,\n"
    "        am_thuoc=am_thuoc, am_xetnghiem=am_xetnghiem,\n"
    "    )\n"
    "    if not ok:\n"
    "        gate = reason.split(']')[0].lstrip('[')\n"
    "        reject_log[gate] = reject_log.get(gate, 0) + 1\n"
    "        continue\n"
    "\n"
    "    out_ents = [{'text': e['text'], 'type': e['type'],\n"
    "                 'position': e['position']} for e in ents]\n"
    "    fname = f'{saved+1:04d}.json'\n"
    "    with open(f'/kaggle/working/output_json/{fname}', 'w', encoding='utf-8') as f:\n"
    "        json.dump(out_ents, f, ensure_ascii=False, indent=2)\n"
    "    saved += 1\n"
    "\n"
    "total_reject = sum(reject_log.values())\n"
    "print(f'LUU: {saved} file, BO QUA: {total_reject}')\n"
    "print('Ly do bo qua:', reject_log)\n"
    "total_gen = saved + total_reject\n"
    "if total_gen > 0:\n"
    "    pct = total_reject / total_gen * 100\n"
    "    if pct > 40:\n"
    "        print(f'!!! {pct:.0f}% bi loai > 40% -- xem lai prompt/nguong')\n"
    "    else:\n"
    "        print(f'  Ty le bo qua: {pct:.0f}% (< 40%)')"
))

# ── Cell 7: T2A khoi cau truc ─────────────────────────────────────────────
cells.append(code(
    "from synth_struct import build_blocks\n"
    "from synth_source import gen_lab_pairs\n"
    "\n"
    "def make_struct_entities(scenarios):\n"
    "    result = []\n"
    "    for sc in scenarios:\n"
    "        s = sc['scenario']\n"
    "        ents = [(sc['diagnosis']['term'], 'CHAN_DOAN')]\n"
    "        for t in s['tc']: ents.append((t, 'TRIEU_CHUNG'))\n"
    "        for t in s['th']: ents.append((t, 'THUOC'))\n"
    "        for t in s['tx']: ents.append((t, 'TEN_XET_NGHIEM'))\n"
    "        for full, ten, kq in gen_lab_pairs(3):\n"
    "            ents.append((ten, 'TEN_XET_NGHIEM'))\n"
    "            if kq: ents.append((kq, 'KET_QUA_XET_NGHIEM'))\n"
    "        result.append(ents)\n"
    "    return result\n"
    "\n"
    "struct_ents_list = make_struct_entities(scenarios)\n"
    "n_struct = max(20, int(saved * 10 // 65))\n"
    "blocks = build_blocks(struct_ents_list, n_struct, heading_ls, heading_hd)\n"
    "\n"
    "struct_saved = 0\n"
    "struct_start = saved + 1\n"
    "for text, ents in blocks:\n"
    "    ok_ents = all(text[e['position'][0]:e['position'][1]] == e['text']\n"
    "                  for e in ents)\n"
    "    if not ok_ents: continue\n"
    "    out_ents = [{'text': e['text'], 'type': e['type'],\n"
    "                 'position': e['position']} for e in ents]\n"
    "    fname = f'{struct_start + struct_saved:04d}.json'\n"
    "    with open(f'/kaggle/working/output_json/{fname}', 'w', encoding='utf-8') as f:\n"
    "        json.dump(out_ents, f, ensure_ascii=False, indent=2)\n"
    "    struct_saved += 1\n"
    "\n"
    "print(f'T2A: luu {struct_saved} khoi cau truc')\n"
    "print(f'Tong file output_json/: {saved + struct_saved}')"
))

# ── Cell 8: thong ke ──────────────────────────────────────────────────────
cells.append(code(
    "from collections import Counter\n"
    "all_ents = []\n"
    "fnames = sorted(os.listdir('/kaggle/working/output_json'))\n"
    "for fn in fnames:\n"
    "    if not fn.endswith('.json'): continue\n"
    "    ents = json.load(open(f'/kaggle/working/output_json/{fn}', encoding='utf-8'))\n"
    "    all_ents.extend(ents)\n"
    "\n"
    "cnt = Counter(e['type'] for e in all_ents)\n"
    "total = len(all_ents)\n"
    "print(f'Tong thuc the: {total} trong {len(fnames)} file')\n"
    "print('Phan bo loai:')\n"
    "TARGET = {'CHAN_DOAN': 25, 'TRIEU_CHUNG': 33, 'THUOC': 16,\n"
    "           'TEN_XET_NGHIEM': 15, 'KET_QUA_XET_NGHIEM': 11}\n"
    "for t, tgt in sorted(TARGET.items(), key=lambda x: -x[1]):\n"
    "    n = cnt.get(t, 0)\n"
    "    pct = n / max(1, total) * 100\n"
    "    flag = 'ok' if abs(pct - tgt) <= 15 else 'LECH'\n"
    "    print(f'  {flag} {t}: {n} ({pct:.1f}%, muc tieu {tgt}%)')\n"
    "print('\\nSan sang dung lam training data cho encoder!')"
))

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
        "language_info": {"name": "python", "version": "3.11"}
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

out = os.path.join(ROOT, "notebooks", "synth_data_gen.ipynb")
with open(out, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
sz = os.path.getsize(out)
print(f"Written {out} ({sz//1024}KB)")

# Verify JSON parse
with open(out, encoding="utf-8") as f:
    loaded = json.load(f)
n_code = sum(1 for c in loaded["cells"] if c["cell_type"] == "code")
print(f"Verified: {len(loaded['cells'])} cells ({n_code} code cells)")
